In [1]:
import numpy as np
import pandas as pd
import datetime

In [2]:
# Read the CSV file
data = pd.read_csv('bank_marketing.csv')
data

,client_id,age,job,marital,education,credit_default,mortgage,month,day,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome
0,32884,NaN,NaN,married,NaN,no,no,may,9,371,1,1,failure,92.893,1.299,no
1,3169,55.0,unknown,married,unknown,unknown,yes,may,24,285,2,0,nonexistent,93.994,4.860,no
2,32206,33.0,blue-collar,married,basic.9y,no,no,may,1,52,1,1,failure,92.893,1.313,no
3,9403,NaN,NaN,married,NaN,no,no,jun,3,355,4,0,nonexistent,94.465,4.967,no
4,14020,27.0,housemaid,married,high.school,no,yes,jul,30,189,2,0,nonexistent,93.918,4.963,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9780,40291,NaN,NaN,divorced,NaN,no,no,jul,21,169,2,2,success,94.215,0.899,yes
9781,1412,NaN,NaN,divorced,NaN,no,yes,may,5,453,2,0,nonexistent,93.994,4.855,no
9782,26188,NaN,NaN,married,NaN,no,yes,nov,2,348,3,0,nonexistent,93.200,4.076,no
9783,18326,NaN,NaN,married,NaN,no,yes,jul,7,962,4,0,nonexistent,93.918,4.963,yes
9784,39909,NaN,NaN,single,NaN,no,yes,jun,6,193,1,1,failure,94.055,0.739,no

In [3]:
# Check if there are duplicated values in the data set
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
9780     True
9781     True
9782     True
9783     True
9784     True
Length: 9785, dtype: bool

In [4]:
# Remove the duplicates in the dataset which targets the primary key client_id
data = data.drop_duplicates(subset=['client_id'], keep='first').copy()
data

,client_id,age,job,marital,education,credit_default,mortgage,month,day,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome
0,32884,NaN,NaN,married,NaN,no,no,may,9,371,1,1,failure,92.893,1.299,no
1,3169,55.0,unknown,married,unknown,unknown,yes,may,24,285,2,0,nonexistent,93.994,4.860,no
2,32206,33.0,blue-collar,married,basic.9y,no,no,may,1,52,1,1,failure,92.893,1.313,no
3,9403,NaN,NaN,married,NaN,no,no,jun,3,355,4,0,nonexistent,94.465,4.967,no
4,14020,27.0,housemaid,married,high.school,no,yes,jul,30,189,2,0,nonexistent,93.918,4.963,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,admin.,married,unknown,no,no,apr,23,387,2,0,nonexistent,93.749,0.654,yes
9496,3921,41.0,blue-collar,married,basic.4y,unknown,no,may,29,88,5,0,nonexistent,93.994,4.858,no
9497,18387,32.0,admin.,divorced,high.school,no,unknown,jul,1,81,4,0,nonexistent,93.918,4.968,no
9498,38711,61.0,management,married,university.degree,no,yes,nov,28,195,1,1,success,92.649,0.715,yes
9499,1274,38.0,entrepreneur,married,basic.6y,no,yes,may,14,196,1,0,nonexistent,93.994,4.855,no

In [5]:
# Define a mapping of month names to numerical values
month_mapping = {
    'jan': 1, 'feb': 2, 'mar': 3, 'apr': 4, 'may': 5, 'jun': 6,
    'jul': 7, 'aug': 8, 'sep': 9, 'oct': 10, 'nov': 11, 'dec': 12
}

In [6]:
# Add a temporary year column (2022) that will be used for formatting later
data['year'] = 2022

In [7]:
# Replace month names with numeric values
data['month'] = data['month'].map(month_mapping)
data

,client_id,age,job,marital,education,credit_default,mortgage,month,day,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,year
0,32884,NaN,NaN,married,NaN,no,no,5,9,371,1,1,failure,92.893,1.299,no,2022
1,3169,55.0,unknown,married,unknown,unknown,yes,5,24,285,2,0,nonexistent,93.994,4.860,no,2022
2,32206,33.0,blue-collar,married,basic.9y,no,no,5,1,52,1,1,failure,92.893,1.313,no,2022
3,9403,NaN,NaN,married,NaN,no,no,6,3,355,4,0,nonexistent,94.465,4.967,no,2022
4,14020,27.0,housemaid,married,high.school,no,yes,7,30,189,2,0,nonexistent,93.918,4.963,no,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,admin.,married,unknown,no,no,4,23,387,2,0,nonexistent,93.749,0.654,yes,2022
9496,3921,41.0,blue-collar,married,basic.4y,unknown,no,5,29,88,5,0,nonexistent,93.994,4.858,no,2022
9497,18387,32.0,admin.,divorced,high.school,no,unknown,7,1,81,4,0,nonexistent,93.918,4.968,no,2022
9498,38711,61.0,management,married,university.degree,no,yes,11,28,195,1,1,success,92.649,0.715,yes,2022
9499,1274,38.0,entrepreneur,married,basic.6y,no,yes,5,14,196,1,0,nonexistent,93.994,4.855,no,2022

In [8]:
# Combine year, month, and day into a single date column
data['date'] = pd.to_datetime(data[['year', 'month', 'day']])
data

,client_id,age,job,marital,education,credit_default,mortgage,month,day,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,year,date
0,32884,NaN,NaN,married,NaN,no,no,5,9,371,1,1,failure,92.893,1.299,no,2022,2022-05-09
1,3169,55.0,unknown,married,unknown,unknown,yes,5,24,285,2,0,nonexistent,93.994,4.860,no,2022,2022-05-24
2,32206,33.0,blue-collar,married,basic.9y,no,no,5,1,52,1,1,failure,92.893,1.313,no,2022,2022-05-01
3,9403,NaN,NaN,married,NaN,no,no,6,3,355,4,0,nonexistent,94.465,4.967,no,2022,2022-06-03
4,14020,27.0,housemaid,married,high.school,no,yes,7,30,189,2,0,nonexistent,93.918,4.963,no,2022,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,admin.,married,unknown,no,no,4,23,387,2,0,nonexistent,93.749,0.654,yes,2022,2022-04-23
9496,3921,41.0,blue-collar,married,basic.4y,unknown,no,5,29,88,5,0,nonexistent,93.994,4.858,no,2022,2022-05-29
9497,18387,32.0,admin.,divorced,high.school,no,unknown,7,1,81,4,0,nonexistent,93.918,4.968,no,2022,2022-07-01
9498,38711,61.0,management,married,university.degree,no,yes,11,28,195,1,1,success,92.649,0.715,yes,2022,2022-11-28
9499,1274,38.0,entrepreneur,married,basic.6y,no,yes,5,14,196,1,0,nonexistent,93.994,4.855,no,2022,2022-05-14

In [9]:
# Drop unnecessary and temporary columns
data = data.drop(columns=['month', 'year', 'day'])
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,NaN,NaN,married,NaN,no,no,371,1,1,failure,92.893,1.299,no,2022-05-09
1,3169,55.0,unknown,married,unknown,unknown,yes,285,2,0,nonexistent,93.994,4.860,no,2022-05-24
2,32206,33.0,blue-collar,married,basic.9y,no,no,52,1,1,failure,92.893,1.313,no,2022-05-01
3,9403,NaN,NaN,married,NaN,no,no,355,4,0,nonexistent,94.465,4.967,no,2022-06-03
4,14020,27.0,housemaid,married,high.school,no,yes,189,2,0,nonexistent,93.918,4.963,no,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,admin.,married,unknown,no,no,387,2,0,nonexistent,93.749,0.654,yes,2022-04-23
9496,3921,41.0,blue-collar,married,basic.4y,unknown,no,88,5,0,nonexistent,93.994,4.858,no,2022-05-29
9497,18387,32.0,admin.,divorced,high.school,no,unknown,81,4,0,nonexistent,93.918,4.968,no,2022-07-01
9498,38711,61.0,management,married,university.degree,no,yes,195,1,1,success,92.649,0.715,yes,2022-11-28
9499,1274,38.0,entrepreneur,married,basic.6y,no,yes,196,1,0,nonexistent,93.994,4.855,no,2022-05-14

In [10]:
# Convert the values of 'contact_duration' into numeric 
data['contact_duration'] = pd.to_numeric(data['contact_duration'], errors='coerce')
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,NaN,NaN,married,NaN,no,no,371,1,1,failure,92.893,1.299,no,2022-05-09
1,3169,55.0,unknown,married,unknown,unknown,yes,285,2,0,nonexistent,93.994,4.860,no,2022-05-24
2,32206,33.0,blue-collar,married,basic.9y,no,no,52,1,1,failure,92.893,1.313,no,2022-05-01
3,9403,NaN,NaN,married,NaN,no,no,355,4,0,nonexistent,94.465,4.967,no,2022-06-03
4,14020,27.0,housemaid,married,high.school,no,yes,189,2,0,nonexistent,93.918,4.963,no,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,admin.,married,unknown,no,no,387,2,0,nonexistent,93.749,0.654,yes,2022-04-23
9496,3921,41.0,blue-collar,married,basic.4y,unknown,no,88,5,0,nonexistent,93.994,4.858,no,2022-05-29
9497,18387,32.0,admin.,divorced,high.school,no,unknown,81,4,0,nonexistent,93.918,4.968,no,2022-07-01
9498,38711,61.0,management,married,university.degree,no,yes,195,1,1,success,92.649,0.715,yes,2022-11-28
9499,1274,38.0,entrepreneur,married,basic.6y,no,yes,196,1,0,nonexistent,93.994,4.855,no,2022-05-14

In [11]:
# Convert seconds to 'HH:MM:SS' format
data['contact_duration'] = data['contact_duration'].apply(lambda x: f'{int(x//3600)}:{int((x%3600)//60):02d}:{int(x%60):02d}')
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,NaN,NaN,married,NaN,no,no,0:06:11,1,1,failure,92.893,1.299,no,2022-05-09
1,3169,55.0,unknown,married,unknown,unknown,yes,0:04:45,2,0,nonexistent,93.994,4.860,no,2022-05-24
2,32206,33.0,blue-collar,married,basic.9y,no,no,0:00:52,1,1,failure,92.893,1.313,no,2022-05-01
3,9403,NaN,NaN,married,NaN,no,no,0:05:55,4,0,nonexistent,94.465,4.967,no,2022-06-03
4,14020,27.0,housemaid,married,high.school,no,yes,0:03:09,2,0,nonexistent,93.918,4.963,no,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,admin.,married,unknown,no,no,0:06:27,2,0,nonexistent,93.749,0.654,yes,2022-04-23
9496,3921,41.0,blue-collar,married,basic.4y,unknown,no,0:01:28,5,0,nonexistent,93.994,4.858,no,2022-05-29
9497,18387,32.0,admin.,divorced,high.school,no,unknown,0:01:21,4,0,nonexistent,93.918,4.968,no,2022-07-01
9498,38711,61.0,management,married,university.degree,no,yes,0:03:15,1,1,success,92.649,0.715,yes,2022-11-28
9499,1274,38.0,entrepreneur,married,basic.6y,no,yes,0:03:16,1,0,nonexistent,93.994,4.855,no,2022-05-14

In [12]:
# Convert 'campaign_outcome' values from 'yes'/'no' to 'Successful'/'Failed'
data['campaign_outcome'] = data['campaign_outcome'].map({'yes': 'Successful', 'no': 'Failed'})
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,NaN,NaN,married,NaN,no,no,0:06:11,1,1,failure,92.893,1.299,Failed,2022-05-09
1,3169,55.0,unknown,married,unknown,unknown,yes,0:04:45,2,0,nonexistent,93.994,4.860,Failed,2022-05-24
2,32206,33.0,blue-collar,married,basic.9y,no,no,0:00:52,1,1,failure,92.893,1.313,Failed,2022-05-01
3,9403,NaN,NaN,married,NaN,no,no,0:05:55,4,0,nonexistent,94.465,4.967,Failed,2022-06-03
4,14020,27.0,housemaid,married,high.school,no,yes,0:03:09,2,0,nonexistent,93.918,4.963,Failed,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,admin.,married,unknown,no,no,0:06:27,2,0,nonexistent,93.749,0.654,Successful,2022-04-23
9496,3921,41.0,blue-collar,married,basic.4y,unknown,no,0:01:28,5,0,nonexistent,93.994,4.858,Failed,2022-05-29
9497,18387,32.0,admin.,divorced,high.school,no,unknown,0:01:21,4,0,nonexistent,93.918,4.968,Failed,2022-07-01
9498,38711,61.0,management,married,university.degree,no,yes,0:03:15,1,1,success,92.649,0.715,Successful,2022-11-28
9499,1274,38.0,entrepreneur,married,basic.6y,no,yes,0:03:16,1,0,nonexistent,93.994,4.855,Failed,2022-05-14

In [13]:
# Capitalize first letter of every word in all string columns
data = data.apply(lambda x: x.str.title() if x.dtype == "object" else x)
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,NaN,NaN,Married,NaN,No,No,0:06:11,1,1,Failure,92.893,1.299,Failed,2022-05-09
1,3169,55.0,Unknown,Married,Unknown,Unknown,Yes,0:04:45,2,0,Nonexistent,93.994,4.860,Failed,2022-05-24
2,32206,33.0,Blue-Collar,Married,Basic.9Y,No,No,0:00:52,1,1,Failure,92.893,1.313,Failed,2022-05-01
3,9403,NaN,NaN,Married,NaN,No,No,0:05:55,4,0,Nonexistent,94.465,4.967,Failed,2022-06-03
4,14020,27.0,Housemaid,Married,High.School,No,Yes,0:03:09,2,0,Nonexistent,93.918,4.963,Failed,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,Admin.,Married,Unknown,No,No,0:06:27,2,0,Nonexistent,93.749,0.654,Successful,2022-04-23
9496,3921,41.0,Blue-Collar,Married,Basic.4Y,Unknown,No,0:01:28,5,0,Nonexistent,93.994,4.858,Failed,2022-05-29
9497,18387,32.0,Admin.,Divorced,High.School,No,Unknown,0:01:21,4,0,Nonexistent,93.918,4.968,Failed,2022-07-01
9498,38711,61.0,Management,Married,University.Degree,No,Yes,0:03:15,1,1,Success,92.649,0.715,Successful,2022-11-28
9499,1274,38.0,Entrepreneur,Married,Basic.6Y,No,Yes,0:03:16,1,0,Nonexistent,93.994,4.855,Failed,2022-05-14

In [14]:
# Replace "Unknown" values with NaN
data = data.replace("Unknown", np.nan)
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,NaN,NaN,Married,NaN,No,No,0:06:11,1,1,Failure,92.893,1.299,Failed,2022-05-09
1,3169,55.0,NaN,Married,NaN,NaN,Yes,0:04:45,2,0,Nonexistent,93.994,4.860,Failed,2022-05-24
2,32206,33.0,Blue-Collar,Married,Basic.9Y,No,No,0:00:52,1,1,Failure,92.893,1.313,Failed,2022-05-01
3,9403,NaN,NaN,Married,NaN,No,No,0:05:55,4,0,Nonexistent,94.465,4.967,Failed,2022-06-03
4,14020,27.0,Housemaid,Married,High.School,No,Yes,0:03:09,2,0,Nonexistent,93.918,4.963,Failed,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,Admin.,Married,NaN,No,No,0:06:27,2,0,Nonexistent,93.749,0.654,Successful,2022-04-23
9496,3921,41.0,Blue-Collar,Married,Basic.4Y,NaN,No,0:01:28,5,0,Nonexistent,93.994,4.858,Failed,2022-05-29
9497,18387,32.0,Admin.,Divorced,High.School,No,NaN,0:01:21,4,0,Nonexistent,93.918,4.968,Failed,2022-07-01
9498,38711,61.0,Management,Married,University.Degree,No,Yes,0:03:15,1,1,Success,92.649,0.715,Successful,2022-11-28
9499,1274,38.0,Entrepreneur,Married,Basic.6Y,No,Yes,0:03:16,1,0,Nonexistent,93.994,4.855,Failed,2022-05-14

In [15]:
#Impute age column with median value, so even if there are outliers, the imputed values are not affect
data['age'] = data['age'].fillna(data['age'].median())
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,38.0,NaN,Married,NaN,No,No,0:06:11,1,1,Failure,92.893,1.299,Failed,2022-05-09
1,3169,55.0,NaN,Married,NaN,NaN,Yes,0:04:45,2,0,Nonexistent,93.994,4.860,Failed,2022-05-24
2,32206,33.0,Blue-Collar,Married,Basic.9Y,No,No,0:00:52,1,1,Failure,92.893,1.313,Failed,2022-05-01
3,9403,38.0,NaN,Married,NaN,No,No,0:05:55,4,0,Nonexistent,94.465,4.967,Failed,2022-06-03
4,14020,27.0,Housemaid,Married,High.School,No,Yes,0:03:09,2,0,Nonexistent,93.918,4.963,Failed,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,Admin.,Married,NaN,No,No,0:06:27,2,0,Nonexistent,93.749,0.654,Successful,2022-04-23
9496,3921,41.0,Blue-Collar,Married,Basic.4Y,NaN,No,0:01:28,5,0,Nonexistent,93.994,4.858,Failed,2022-05-29
9497,18387,32.0,Admin.,Divorced,High.School,No,NaN,0:01:21,4,0,Nonexistent,93.918,4.968,Failed,2022-07-01
9498,38711,61.0,Management,Married,University.Degree,No,Yes,0:03:15,1,1,Success,92.649,0.715,Successful,2022-11-28
9499,1274,38.0,Entrepreneur,Married,Basic.6Y,No,Yes,0:03:16,1,0,Nonexistent,93.994,4.855,Failed,2022-05-14

In [16]:
#Impute job column with the most frequent value (mode)
data['job'] = data['job'].fillna(data['job'].mode()[0])
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,38.0,Admin.,Married,NaN,No,No,0:06:11,1,1,Failure,92.893,1.299,Failed,2022-05-09
1,3169,55.0,Admin.,Married,NaN,NaN,Yes,0:04:45,2,0,Nonexistent,93.994,4.860,Failed,2022-05-24
2,32206,33.0,Blue-Collar,Married,Basic.9Y,No,No,0:00:52,1,1,Failure,92.893,1.313,Failed,2022-05-01
3,9403,38.0,Admin.,Married,NaN,No,No,0:05:55,4,0,Nonexistent,94.465,4.967,Failed,2022-06-03
4,14020,27.0,Housemaid,Married,High.School,No,Yes,0:03:09,2,0,Nonexistent,93.918,4.963,Failed,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,Admin.,Married,NaN,No,No,0:06:27,2,0,Nonexistent,93.749,0.654,Successful,2022-04-23
9496,3921,41.0,Blue-Collar,Married,Basic.4Y,NaN,No,0:01:28,5,0,Nonexistent,93.994,4.858,Failed,2022-05-29
9497,18387,32.0,Admin.,Divorced,High.School,No,NaN,0:01:21,4,0,Nonexistent,93.918,4.968,Failed,2022-07-01
9498,38711,61.0,Management,Married,University.Degree,No,Yes,0:03:15,1,1,Success,92.649,0.715,Successful,2022-11-28
9499,1274,38.0,Entrepreneur,Married,Basic.6Y,No,Yes,0:03:16,1,0,Nonexistent,93.994,4.855,Failed,2022-05-14

In [17]:
#Impute credit_default column with the most frequent value (mode)
data['credit_default'] = data['credit_default'].fillna(data['credit_default'].mode()[0])
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,38.0,Admin.,Married,NaN,No,No,0:06:11,1,1,Failure,92.893,1.299,Failed,2022-05-09
1,3169,55.0,Admin.,Married,NaN,No,Yes,0:04:45,2,0,Nonexistent,93.994,4.860,Failed,2022-05-24
2,32206,33.0,Blue-Collar,Married,Basic.9Y,No,No,0:00:52,1,1,Failure,92.893,1.313,Failed,2022-05-01
3,9403,38.0,Admin.,Married,NaN,No,No,0:05:55,4,0,Nonexistent,94.465,4.967,Failed,2022-06-03
4,14020,27.0,Housemaid,Married,High.School,No,Yes,0:03:09,2,0,Nonexistent,93.918,4.963,Failed,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,Admin.,Married,NaN,No,No,0:06:27,2,0,Nonexistent,93.749,0.654,Successful,2022-04-23
9496,3921,41.0,Blue-Collar,Married,Basic.4Y,No,No,0:01:28,5,0,Nonexistent,93.994,4.858,Failed,2022-05-29
9497,18387,32.0,Admin.,Divorced,High.School,No,NaN,0:01:21,4,0,Nonexistent,93.918,4.968,Failed,2022-07-01
9498,38711,61.0,Management,Married,University.Degree,No,Yes,0:03:15,1,1,Success,92.649,0.715,Successful,2022-11-28
9499,1274,38.0,Entrepreneur,Married,Basic.6Y,No,Yes,0:03:16,1,0,Nonexistent,93.994,4.855,Failed,2022-05-14

In [18]:
#Impute mortgage column with the most frequent value (mode)
data['mortgage'] = data['mortgage'].fillna(data['mortgage'].mode()[0])
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,38.0,Admin.,Married,NaN,No,No,0:06:11,1,1,Failure,92.893,1.299,Failed,2022-05-09
1,3169,55.0,Admin.,Married,NaN,No,Yes,0:04:45,2,0,Nonexistent,93.994,4.860,Failed,2022-05-24
2,32206,33.0,Blue-Collar,Married,Basic.9Y,No,No,0:00:52,1,1,Failure,92.893,1.313,Failed,2022-05-01
3,9403,38.0,Admin.,Married,NaN,No,No,0:05:55,4,0,Nonexistent,94.465,4.967,Failed,2022-06-03
4,14020,27.0,Housemaid,Married,High.School,No,Yes,0:03:09,2,0,Nonexistent,93.918,4.963,Failed,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,Admin.,Married,NaN,No,No,0:06:27,2,0,Nonexistent,93.749,0.654,Successful,2022-04-23
9496,3921,41.0,Blue-Collar,Married,Basic.4Y,No,No,0:01:28,5,0,Nonexistent,93.994,4.858,Failed,2022-05-29
9497,18387,32.0,Admin.,Divorced,High.School,No,Yes,0:01:21,4,0,Nonexistent,93.918,4.968,Failed,2022-07-01
9498,38711,61.0,Management,Married,University.Degree,No,Yes,0:03:15,1,1,Success,92.649,0.715,Successful,2022-11-28
9499,1274,38.0,Entrepreneur,Married,Basic.6Y,No,Yes,0:03:16,1,0,Nonexistent,93.994,4.855,Failed,2022-05-14

In [19]:
#Imputation for education; based on most common education for each job
most_common_education_per_job = data.groupby('job')['education'].agg(lambda x: x.mode()[0])
#Map the most common education per job based on the groupby method
data.loc[data['education'].isnull(), 'education'] = data.loc[data['education'].isnull(), 'job'].map(most_common_education_per_job)
data

,client_id,age,job,marital,education,credit_default,mortgage,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome,date
0,32884,38.0,Admin.,Married,University.Degree,No,No,0:06:11,1,1,Failure,92.893,1.299,Failed,2022-05-09
1,3169,55.0,Admin.,Married,University.Degree,No,Yes,0:04:45,2,0,Nonexistent,93.994,4.860,Failed,2022-05-24
2,32206,33.0,Blue-Collar,Married,Basic.9Y,No,No,0:00:52,1,1,Failure,92.893,1.313,Failed,2022-05-01
3,9403,38.0,Admin.,Married,University.Degree,No,No,0:05:55,4,0,Nonexistent,94.465,4.967,Failed,2022-06-03
4,14020,27.0,Housemaid,Married,High.School,No,Yes,0:03:09,2,0,Nonexistent,93.918,4.963,Failed,2022-07-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,39541,52.0,Admin.,Married,University.Degree,No,No,0:06:27,2,0,Nonexistent,93.749,0.654,Successful,2022-04-23
9496,3921,41.0,Blue-Collar,Married,Basic.4Y,No,No,0:01:28,5,0,Nonexistent,93.994,4.858,Failed,2022-05-29
9497,18387,32.0,Admin.,Divorced,High.School,No,Yes,0:01:21,4,0,Nonexistent,93.918,4.968,Failed,2022-07-01
9498,38711,61.0,Management,Married,University.Degree,No,Yes,0:03:15,1,1,Success,92.649,0.715,Successful,2022-11-28
9499,1274,38.0,Entrepreneur,Married,Basic.6Y,No,Yes,0:03:16,1,0,Nonexistent,93.994,4.855,Failed,2022-05-14

In [20]:
data.to_csv('bank_marketing_clean.csv', index=False)

PermissionError: [Errno 13] Permission denied: 'bank_marketing_clean.csv'