In [268]:
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('bank_marketing_clean.csv')
# convert the values and sort from march to december
data['date'] = pd.to_datetime(data['date'])
data = data.sort_values(by='date') # Store the sorted values 
# get the columns
cpi = data['cons_price_idx']
euribor = data['euribor_three_months']
date = data['date']

In [269]:
# compute for the quartile
date_Q1 = date.quantile(0.25)
date_Q2 = date.quantile(0.50)
date_Q3 = date.quantile(0.75)
date_Q4 = date.quantile(1)

# Table the Quartiles
date_df = pd.DataFrame({
    "Quarter": ["Quarter 1", "Quarter 2", "Quarter 3", "Quarter 4"],
    'date': [date_Q1, date_Q2, date_Q3, date_Q4]               
     })
#Show the Quartiles
date_df

     Quarter       date
0  Quarter 1 2022-05-16
1  Quarter 2 2022-06-18
2  Quarter 3 2022-08-07
3  Quarter 4 2022-12-31

In [270]:
# compute for the quartile
cpi_Q1 = cpi.quantile(0.25)
cpi_Q2 = cpi.quantile(0.50)
cpi_Q3 = cpi.quantile(0.75)
cpi_Q4 = cpi.quantile(1)
# Table the Quartiles
cpi_df = pd.DataFrame({
    "Percentile": ["Quarter 1", "Quarter 2", "Quarter 3", "Quarter 4"],
    "Consumer Price Index Value": [cpi_Q1, cpi_Q2, cpi_Q3, cpi_Q4],
    'Date': [date_Q1, date_Q2, date_Q3, date_Q4] 
})
#Show the Quartiles
cpi_df

  Percentile  Consumer Price Index Value       Date
0  Quarter 1                      93.075 2022-05-16
1  Quarter 2                      93.749 2022-06-18
2  Quarter 3                      93.994 2022-08-07
3  Quarter 4                      94.767 2022-12-31

In [271]:
# compute quartiles for Euribor
euribor_Q1 = euribor.quantile(0.25)
euribor_Q2 = euribor.quantile(0.50)
euribor_Q3 = euribor.quantile(0.75)
euribor_Q4 = euribor.quantile(1)
# Table the Quartiles
euribor_df = pd.DataFrame({
    "Percentile": ["Quarter 1", "Quarter 2", "Quarter 3", "Quarter 4"],
    "Euribor Value": [euribor_Q1, euribor_Q2, euribor_Q3, euribor_Q4],
    'Date': [date_Q1, date_Q2, date_Q3, date_Q4] 
})
#Show the Quartiles
euribor_df

  Percentile  Euribor Value       Date
0  Quarter 1          1.344 2022-05-16
1  Quarter 2          4.857 2022-06-18
2  Quarter 3          4.961 2022-08-07
3  Quarter 4          5.045 2022-12-31

In [272]:
# Get the interquartile range
cpi_IQR = cpi_Q3 - cpi_Q1
euribor_IQR = euribor_Q3 - euribor_Q1
# Table the IQR
iqr_df = pd.DataFrame({
    "Metric": ["CPI IQR", "Euribor IQR"],
    "Interquartile Range (IQR)": [cpi_IQR, euribor_IQR],
})
# Show IQR
iqr_df

        Metric  Interquartile Range (IQR)
0      CPI IQR                      0.919
1  Euribor IQR                      3.617